### ISSUE TITLE
Cannot change jinja2 delimiters because NonTemplatedInputDirException exception

### ISSUE THREAD

**Issue by ericsouza** [cookiecutter/cookiecutter#1736]
* Cookiecutter version: `2.1.1`
* Python version: `3.10.0`
* Operating System: Ubuntu `20.04`

### Description:

Basically I need to use cookiecutter along side with files that use the same sintax from jinja2 for a template engine from golang (is for using with helm-charts). I saw this [PR](https://github.com/cookiecutter/cookiecutter/pull/1419). So I change jinja2 enviroment using the settings below in my `cookiecutter.json`:
```json
"_jinja2_env_vars": {
        "block_start_string": "[%",
        "block_end_string": "%]",
        "variable_start_string": "[[",
        "variable_end_string": "]]"
    }
```
for the content inside the files all went well, but now I'm getting `cookiecutter.exceptions.NonTemplatedInputDirException` because my project's folder doesn't use `{{` and `}}` 

I think the problem is this part of cookiecutter that does not use the jinja2 configuration: https://github.com/cookiecutter/cookiecutter/blob/449f8771650a3daab7c8163b015576eae26150b8/cookiecutter/find.py#L20

**Comment by xcke** [comment]
For now the workaround seems to be use something like this for the project_dir: 

{{[[cookiecutter.project_name]]}}

inside the project directory files and folders can use the changed jinja2 start and end string

**Comment by liortct** [comment]
I fixed this bug in the PR #1767.
I advice to merge the PR and close this issue.

**Comment by liortct** [comment]
Hi @xcke , @ericsouza 

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened your issue at: https://github.com/cookieninja-generator/cookieninja/issues/35

We're trying to bring the life back to this amazing project.
We are committed to addressing each issue in up to 1 week from the day it's opened.
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Comment by sacha-c** [comment]
I am still experiencing this issue in `v2.4.0`. Here is a proposal PR #1963
